[project]
name = "clase-dash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=3.0.4",
    "dash-ag-grid>=31.3.1",
    "pandas>=2.2.3",
]
